### PR TITLE
Fix `waitForChildren` resolving prematurely due to ancestor siblings

### LINKED ISSUE #62: element-ready@v9 is resolving before the children have loaded
I can repro this pretty consistently:

- https://github.com/refined-github/refined-github/issues/8818

v9 just fails with that error, but v8 works. This result is dependent on internet speed.

The "is fully loaded" check appears to be unchanged since v8, so perhaps the logic is shortcicuiting before the check is reached?

https://github.com/sindresorhus/element-ready/blob/86b948bc6a8f575dcf04d89bb6c69bdcb069ee14/index.js#L36-L43

### PR DESCRIPTION
**Pull request by sindresorhus**
Fixes #62

The sibling check now properly waits for DOM ready when no ancestor has siblings (the refined-github case). Also stops at the `target` boundary and excludes `document.head`. Added a test that directly simulates the refined-github scenario.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -33,8 +43,8 @@ export default async function elementReady(selector, {
 			return element;
 		}
 
-		// Only check the element's own nextSibling, not ancestors, to avoid false positives
-		if (element && (!waitForChildren || element.nextSibling)) {
+		// When `waitForChildren` is enabled, resolve only once the element is guaranteed to be fully parsed.
+		if (element && isChildrenReady({element, target, waitForChildren})) {
```
Comment (fregante) [inline index.js]:
```suggestion
		if (element && (!waitForChildren || isChildrenReady({element, target}))) {
```

File: index.js [hunk 2]
```diff
@@ -106,3 +116,31 @@ function getMatchingElement({target, selector, predicate}) {
...
+
+function isChildrenReady({element, target, waitForChildren}) {
+	if (!waitForChildren) {
+		return true;
+	}
+
+	const ownerDocument = getOwnerDocument(target) ?? element.ownerDocument;
+	if (ownerDocument?.readyState !== 'loading') {
+		return true;
+	}
```
Comment (fregante) [inline index.js:124]: This *seems* to already exist elsewhere, should it be merged there?

File: index.js [hunk 3]
```diff
@@ -106,3 +116,31 @@ function getMatchingElement({target, selector, predicate}) {
...
+
+	// Consider the element "fully parsed" once it, or any ancestor within `target`, has a next sibling.
+	// Ignore `document.head` as it has a `nextSibling` (`body`) from the start, which is not a parsing signal.
```
Comment (fregante) [inline index.js:127]: Good catch, but doesn't this also mean "wait until dom ready" if you use `elementReady('head > .last-element-in-here')`?

The selected element won't have any siblings, and `head.nextElementSibling` is not checked. This can be addressed separately since it's the least common case.

File: test.js [hunk 4]
```diff
@@ -289,27 +289,120 @@ test('ensure that the whole element has loaded', async () => {
...
+test('element without ancestor siblings should wait for DOM ready', async () => {
+	// Simulates refined-github case: script inside react-app with no siblings
+	const jsdom = new JSDOM('<div id="app"><script id="target"></script></div>');
+	const {window} = jsdom;
+	const {document} = window;
+
+	let readyState = 'loading';
+	Object.defineProperty(document, 'readyState', {
+		get: () => readyState,
+	});
```
Comment (fregante) [inline test.js:321]: If you want to avoid mocking, you can get a real "loading" document via `document.write` (in the browser, I don't know about JSDOM)

```js
document.write();
document.readyState === 'loading'
document.close();
document.readyState === 'complete'
```

This would also let you safely test the "element found before domready" core functionality of `element-ready`, so it should likely be used in every single test case.

Comment (sindresorhus) [reply test.js:321]: Tried, but could not get it working in JSDOM.

File: index.js (hunk 3 above)
Comment (sindresorhus) [reply index.js:127]: Yes. head selectors will now wait for DOM ready. I prefer that over using `head.nextSibling` (body) as a parsing signal, and the use-case is also super niche.

File: index.js (hunk 2 above)
Comment (sindresorhus) [reply index.js:124]: Done

**Comment by fregante** [comment]
Mergeable?
